//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.PrsiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppState", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AppState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int integerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int integer {
            get {
                return this.integerField;
            }
            set {
                if ((this.integerField.Equals(value) != true)) {
                    this.integerField = value;
                    this.RaisePropertyChanged("integer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string str {
            get {
                return this.strField;
            }
            set {
                if ((object.ReferenceEquals(this.strField, value) != true)) {
                    this.strField = value;
                    this.RaisePropertyChanged("str");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrsiService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name RegisterSessionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterSession", ReplyAction="*")]
        Client.PrsiService.RegisterSessionResponse RegisterSession(Client.PrsiService.RegisterSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterSession", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.PrsiService.RegisterSessionResponse> RegisterSessionAsync(Client.PrsiService.RegisterSessionRequest request);
        
        // CODEGEN: Generating message contract since element name sessionName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetState", ReplyAction="*")]
        Client.PrsiService.GetStateResponse GetState(Client.PrsiService.GetStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetState", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.PrsiService.GetStateResponse> GetStateAsync(Client.PrsiService.GetStateRequest request);
        
        // CODEGEN: Generating message contract since element name appState from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveState", ReplyAction="*")]
        Client.PrsiService.SaveStateResponse SaveState(Client.PrsiService.SaveStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveState", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.PrsiService.SaveStateResponse> SaveStateAsync(Client.PrsiService.SaveStateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterSession", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.RegisterSessionRequestBody Body;
        
        public RegisterSessionRequest() {
        }
        
        public RegisterSessionRequest(Client.PrsiService.RegisterSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegisterSessionRequestBody {
        
        public RegisterSessionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterSessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.RegisterSessionResponseBody Body;
        
        public RegisterSessionResponse() {
        }
        
        public RegisterSessionResponse(Client.PrsiService.RegisterSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterSessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterSessionResult;
        
        public RegisterSessionResponseBody() {
        }
        
        public RegisterSessionResponseBody(string RegisterSessionResult) {
            this.RegisterSessionResult = RegisterSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetState", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.GetStateRequestBody Body;
        
        public GetStateRequest() {
        }
        
        public GetStateRequest(Client.PrsiService.GetStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionName;
        
        public GetStateRequestBody() {
        }
        
        public GetStateRequestBody(string sessionName) {
            this.sessionName = sessionName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.GetStateResponseBody Body;
        
        public GetStateResponse() {
        }
        
        public GetStateResponse(Client.PrsiService.GetStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.PrsiService.AppState GetStateResult;
        
        public GetStateResponseBody() {
        }
        
        public GetStateResponseBody(Client.PrsiService.AppState GetStateResult) {
            this.GetStateResult = GetStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveState", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.SaveStateRequestBody Body;
        
        public SaveStateRequest() {
        }
        
        public SaveStateRequest(Client.PrsiService.SaveStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.PrsiService.AppState appState;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sessionName;
        
        public SaveStateRequestBody() {
        }
        
        public SaveStateRequestBody(Client.PrsiService.AppState appState, string sessionName) {
            this.appState = appState;
            this.sessionName = sessionName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.SaveStateResponseBody Body;
        
        public SaveStateResponse() {
        }
        
        public SaveStateResponse(Client.PrsiService.SaveStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaveStateResult;
        
        public SaveStateResponseBody() {
        }
        
        public SaveStateResponseBody(string SaveStateResult) {
            this.SaveStateResult = SaveStateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Client.PrsiService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Client.PrsiService.WebServiceSoap>, Client.PrsiService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.PrsiService.RegisterSessionResponse Client.PrsiService.WebServiceSoap.RegisterSession(Client.PrsiService.RegisterSessionRequest request) {
            return base.Channel.RegisterSession(request);
        }
        
        public string RegisterSession() {
            Client.PrsiService.RegisterSessionRequest inValue = new Client.PrsiService.RegisterSessionRequest();
            inValue.Body = new Client.PrsiService.RegisterSessionRequestBody();
            Client.PrsiService.RegisterSessionResponse retVal = ((Client.PrsiService.WebServiceSoap)(this)).RegisterSession(inValue);
            return retVal.Body.RegisterSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.PrsiService.RegisterSessionResponse> Client.PrsiService.WebServiceSoap.RegisterSessionAsync(Client.PrsiService.RegisterSessionRequest request) {
            return base.Channel.RegisterSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.PrsiService.RegisterSessionResponse> RegisterSessionAsync() {
            Client.PrsiService.RegisterSessionRequest inValue = new Client.PrsiService.RegisterSessionRequest();
            inValue.Body = new Client.PrsiService.RegisterSessionRequestBody();
            return ((Client.PrsiService.WebServiceSoap)(this)).RegisterSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.PrsiService.GetStateResponse Client.PrsiService.WebServiceSoap.GetState(Client.PrsiService.GetStateRequest request) {
            return base.Channel.GetState(request);
        }
        
        public Client.PrsiService.AppState GetState(string sessionName) {
            Client.PrsiService.GetStateRequest inValue = new Client.PrsiService.GetStateRequest();
            inValue.Body = new Client.PrsiService.GetStateRequestBody();
            inValue.Body.sessionName = sessionName;
            Client.PrsiService.GetStateResponse retVal = ((Client.PrsiService.WebServiceSoap)(this)).GetState(inValue);
            return retVal.Body.GetStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.PrsiService.GetStateResponse> Client.PrsiService.WebServiceSoap.GetStateAsync(Client.PrsiService.GetStateRequest request) {
            return base.Channel.GetStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.PrsiService.GetStateResponse> GetStateAsync(string sessionName) {
            Client.PrsiService.GetStateRequest inValue = new Client.PrsiService.GetStateRequest();
            inValue.Body = new Client.PrsiService.GetStateRequestBody();
            inValue.Body.sessionName = sessionName;
            return ((Client.PrsiService.WebServiceSoap)(this)).GetStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.PrsiService.SaveStateResponse Client.PrsiService.WebServiceSoap.SaveState(Client.PrsiService.SaveStateRequest request) {
            return base.Channel.SaveState(request);
        }
        
        public string SaveState(Client.PrsiService.AppState appState, string sessionName) {
            Client.PrsiService.SaveStateRequest inValue = new Client.PrsiService.SaveStateRequest();
            inValue.Body = new Client.PrsiService.SaveStateRequestBody();
            inValue.Body.appState = appState;
            inValue.Body.sessionName = sessionName;
            Client.PrsiService.SaveStateResponse retVal = ((Client.PrsiService.WebServiceSoap)(this)).SaveState(inValue);
            return retVal.Body.SaveStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.PrsiService.SaveStateResponse> Client.PrsiService.WebServiceSoap.SaveStateAsync(Client.PrsiService.SaveStateRequest request) {
            return base.Channel.SaveStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.PrsiService.SaveStateResponse> SaveStateAsync(Client.PrsiService.AppState appState, string sessionName) {
            Client.PrsiService.SaveStateRequest inValue = new Client.PrsiService.SaveStateRequest();
            inValue.Body = new Client.PrsiService.SaveStateRequestBody();
            inValue.Body.appState = appState;
            inValue.Body.sessionName = sessionName;
            return ((Client.PrsiService.WebServiceSoap)(this)).SaveStateAsync(inValue);
        }
    }
}
