//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.PrsiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterSessionInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RegisterSessionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sessionNameField;
        
        private int playerIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sessionName {
            get {
                return this.sessionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.sessionNameField, value) != true)) {
                    this.sessionNameField = value;
                    this.RaisePropertyChanged("sessionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int playerID {
            get {
                return this.playerIDField;
            }
            set {
                if ((this.playerIDField.Equals(value) != true)) {
                    this.playerIDField = value;
                    this.RaisePropertyChanged("playerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Client.PrsiService.CardColor colorField;
        
        private Client.PrsiService.CardType typeField;
        
        private Client.PrsiService.CardValue valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Client.PrsiService.CardColor color {
            get {
                return this.colorField;
            }
            set {
                if ((this.colorField.Equals(value) != true)) {
                    this.colorField = value;
                    this.RaisePropertyChanged("color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Client.PrsiService.CardType type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Client.PrsiService.CardValue value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardColor", Namespace="http://tempuri.org/")]
    public enum CardColor : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Black = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Red = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardType", Namespace="http://tempuri.org/")]
    public enum CardType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Heart = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Diamond = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Leaf = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Acorn = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardValue", Namespace="http://tempuri.org/")]
    public enum CardValue : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        C1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        C2 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        C3 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        C4 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        C5 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        C6 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        C7 = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        C8 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        C9 = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        C10 = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CJ = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CQ = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CK = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CA = 14,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppState", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AppState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string winnerField;
        
        private bool nextPlayerAceField;
        
        private bool nextPlayer7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.PrsiService.Player[] playersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.PrsiService.Card[] cardStackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.PrsiService.Card cardPlayedField;
        
        private bool gameStartedField;
        
        private int playerTurnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string winner {
            get {
                return this.winnerField;
            }
            set {
                if ((object.ReferenceEquals(this.winnerField, value) != true)) {
                    this.winnerField = value;
                    this.RaisePropertyChanged("winner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool nextPlayerAce {
            get {
                return this.nextPlayerAceField;
            }
            set {
                if ((this.nextPlayerAceField.Equals(value) != true)) {
                    this.nextPlayerAceField = value;
                    this.RaisePropertyChanged("nextPlayerAce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool nextPlayer7 {
            get {
                return this.nextPlayer7Field;
            }
            set {
                if ((this.nextPlayer7Field.Equals(value) != true)) {
                    this.nextPlayer7Field = value;
                    this.RaisePropertyChanged("nextPlayer7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Client.PrsiService.Player[] players {
            get {
                return this.playersField;
            }
            set {
                if ((object.ReferenceEquals(this.playersField, value) != true)) {
                    this.playersField = value;
                    this.RaisePropertyChanged("players");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Client.PrsiService.Card[] cardStack {
            get {
                return this.cardStackField;
            }
            set {
                if ((object.ReferenceEquals(this.cardStackField, value) != true)) {
                    this.cardStackField = value;
                    this.RaisePropertyChanged("cardStack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Client.PrsiService.Card cardPlayed {
            get {
                return this.cardPlayedField;
            }
            set {
                if ((object.ReferenceEquals(this.cardPlayedField, value) != true)) {
                    this.cardPlayedField = value;
                    this.RaisePropertyChanged("cardPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool gameStarted {
            get {
                return this.gameStartedField;
            }
            set {
                if ((this.gameStartedField.Equals(value) != true)) {
                    this.gameStartedField = value;
                    this.RaisePropertyChanged("gameStarted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int playerTurn {
            get {
                return this.playerTurnField;
            }
            set {
                if ((this.playerTurnField.Equals(value) != true)) {
                    this.playerTurnField = value;
                    this.RaisePropertyChanged("playerTurn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.PrsiService.Card[] cardsField;
        
        private bool isCreatorField;
        
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Client.PrsiService.Card[] cards {
            get {
                return this.cardsField;
            }
            set {
                if ((object.ReferenceEquals(this.cardsField, value) != true)) {
                    this.cardsField = value;
                    this.RaisePropertyChanged("cards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool isCreator {
            get {
                return this.isCreatorField;
            }
            set {
                if ((this.isCreatorField.Equals(value) != true)) {
                    this.isCreatorField = value;
                    this.RaisePropertyChanged("isCreator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrsiService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name playerName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterSession", ReplyAction="*")]
        Client.PrsiService.RegisterSessionResponse RegisterSession(Client.PrsiService.RegisterSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterSession", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.PrsiService.RegisterSessionResponse> RegisterSessionAsync(Client.PrsiService.RegisterSessionRequest request);
        
        // CODEGEN: Generating message contract since element name sessionName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JoinSession", ReplyAction="*")]
        Client.PrsiService.JoinSessionResponse JoinSession(Client.PrsiService.JoinSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JoinSession", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.PrsiService.JoinSessionResponse> JoinSessionAsync(Client.PrsiService.JoinSessionRequest request);
        
        // CODEGEN: Generating message contract since element name sessionName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeaveSession", ReplyAction="*")]
        Client.PrsiService.LeaveSessionResponse LeaveSession(Client.PrsiService.LeaveSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeaveSession", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.PrsiService.LeaveSessionResponse> LeaveSessionAsync(Client.PrsiService.LeaveSessionRequest request);
        
        // CODEGEN: Generating message contract since element name sessionName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartGame", ReplyAction="*")]
        Client.PrsiService.StartGameResponse StartGame(Client.PrsiService.StartGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartGame", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.PrsiService.StartGameResponse> StartGameAsync(Client.PrsiService.StartGameRequest request);
        
        // CODEGEN: Generating message contract since element name sessionName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayCard", ReplyAction="*")]
        Client.PrsiService.PlayCardResponse PlayCard(Client.PrsiService.PlayCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayCard", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.PrsiService.PlayCardResponse> PlayCardAsync(Client.PrsiService.PlayCardRequest request);
        
        // CODEGEN: Generating message contract since element name sessionName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SkipTurn", ReplyAction="*")]
        Client.PrsiService.SkipTurnResponse SkipTurn(Client.PrsiService.SkipTurnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SkipTurn", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.PrsiService.SkipTurnResponse> SkipTurnAsync(Client.PrsiService.SkipTurnRequest request);
        
        // CODEGEN: Generating message contract since element name sessionName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetState", ReplyAction="*")]
        Client.PrsiService.GetStateResponse GetState(Client.PrsiService.GetStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetState", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.PrsiService.GetStateResponse> GetStateAsync(Client.PrsiService.GetStateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterSession", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.RegisterSessionRequestBody Body;
        
        public RegisterSessionRequest() {
        }
        
        public RegisterSessionRequest(Client.PrsiService.RegisterSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterSessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string playerName;
        
        public RegisterSessionRequestBody() {
        }
        
        public RegisterSessionRequestBody(string playerName) {
            this.playerName = playerName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterSessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.RegisterSessionResponseBody Body;
        
        public RegisterSessionResponse() {
        }
        
        public RegisterSessionResponse(Client.PrsiService.RegisterSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterSessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.PrsiService.RegisterSessionInfo RegisterSessionResult;
        
        public RegisterSessionResponseBody() {
        }
        
        public RegisterSessionResponseBody(Client.PrsiService.RegisterSessionInfo RegisterSessionResult) {
            this.RegisterSessionResult = RegisterSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JoinSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JoinSession", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.JoinSessionRequestBody Body;
        
        public JoinSessionRequest() {
        }
        
        public JoinSessionRequest(Client.PrsiService.JoinSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JoinSessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string playerName;
        
        public JoinSessionRequestBody() {
        }
        
        public JoinSessionRequestBody(string sessionName, string playerName) {
            this.sessionName = sessionName;
            this.playerName = playerName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JoinSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JoinSessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.JoinSessionResponseBody Body;
        
        public JoinSessionResponse() {
        }
        
        public JoinSessionResponse(Client.PrsiService.JoinSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JoinSessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int JoinSessionResult;
        
        public JoinSessionResponseBody() {
        }
        
        public JoinSessionResponseBody(int JoinSessionResult) {
            this.JoinSessionResult = JoinSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeaveSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeaveSession", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.LeaveSessionRequestBody Body;
        
        public LeaveSessionRequest() {
        }
        
        public LeaveSessionRequest(Client.PrsiService.LeaveSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LeaveSessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int playerID;
        
        public LeaveSessionRequestBody() {
        }
        
        public LeaveSessionRequestBody(string sessionName, int playerID) {
            this.sessionName = sessionName;
            this.playerID = playerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeaveSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeaveSessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.LeaveSessionResponseBody Body;
        
        public LeaveSessionResponse() {
        }
        
        public LeaveSessionResponse(Client.PrsiService.LeaveSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LeaveSessionResponseBody {
        
        public LeaveSessionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartGameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartGame", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.StartGameRequestBody Body;
        
        public StartGameRequest() {
        }
        
        public StartGameRequest(Client.PrsiService.StartGameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StartGameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int playerID;
        
        public StartGameRequestBody() {
        }
        
        public StartGameRequestBody(string sessionName, int playerID) {
            this.sessionName = sessionName;
            this.playerID = playerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartGameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartGameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.StartGameResponseBody Body;
        
        public StartGameResponse() {
        }
        
        public StartGameResponse(Client.PrsiService.StartGameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StartGameResponseBody {
        
        public StartGameResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayCard", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.PlayCardRequestBody Body;
        
        public PlayCardRequest() {
        }
        
        public PlayCardRequest(Client.PrsiService.PlayCardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlayCardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int playerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Client.PrsiService.Card card;
        
        public PlayCardRequestBody() {
        }
        
        public PlayCardRequestBody(string sessionName, int playerID, Client.PrsiService.Card card) {
            this.sessionName = sessionName;
            this.playerID = playerID;
            this.card = card;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayCardResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.PlayCardResponseBody Body;
        
        public PlayCardResponse() {
        }
        
        public PlayCardResponse(Client.PrsiService.PlayCardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PlayCardResponseBody {
        
        public PlayCardResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SkipTurnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SkipTurn", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.SkipTurnRequestBody Body;
        
        public SkipTurnRequest() {
        }
        
        public SkipTurnRequest(Client.PrsiService.SkipTurnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SkipTurnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int playerID;
        
        public SkipTurnRequestBody() {
        }
        
        public SkipTurnRequestBody(string sessionName, int playerID) {
            this.sessionName = sessionName;
            this.playerID = playerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SkipTurnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SkipTurnResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.SkipTurnResponseBody Body;
        
        public SkipTurnResponse() {
        }
        
        public SkipTurnResponse(Client.PrsiService.SkipTurnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SkipTurnResponseBody {
        
        public SkipTurnResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetState", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.GetStateRequestBody Body;
        
        public GetStateRequest() {
        }
        
        public GetStateRequest(Client.PrsiService.GetStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionName;
        
        public GetStateRequestBody() {
        }
        
        public GetStateRequestBody(string sessionName) {
            this.sessionName = sessionName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.GetStateResponseBody Body;
        
        public GetStateResponse() {
        }
        
        public GetStateResponse(Client.PrsiService.GetStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.PrsiService.AppState GetStateResult;
        
        public GetStateResponseBody() {
        }
        
        public GetStateResponseBody(Client.PrsiService.AppState GetStateResult) {
            this.GetStateResult = GetStateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Client.PrsiService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Client.PrsiService.WebServiceSoap>, Client.PrsiService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.PrsiService.RegisterSessionResponse Client.PrsiService.WebServiceSoap.RegisterSession(Client.PrsiService.RegisterSessionRequest request) {
            return base.Channel.RegisterSession(request);
        }
        
        public Client.PrsiService.RegisterSessionInfo RegisterSession(string playerName) {
            Client.PrsiService.RegisterSessionRequest inValue = new Client.PrsiService.RegisterSessionRequest();
            inValue.Body = new Client.PrsiService.RegisterSessionRequestBody();
            inValue.Body.playerName = playerName;
            Client.PrsiService.RegisterSessionResponse retVal = ((Client.PrsiService.WebServiceSoap)(this)).RegisterSession(inValue);
            return retVal.Body.RegisterSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.PrsiService.RegisterSessionResponse> Client.PrsiService.WebServiceSoap.RegisterSessionAsync(Client.PrsiService.RegisterSessionRequest request) {
            return base.Channel.RegisterSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.PrsiService.RegisterSessionResponse> RegisterSessionAsync(string playerName) {
            Client.PrsiService.RegisterSessionRequest inValue = new Client.PrsiService.RegisterSessionRequest();
            inValue.Body = new Client.PrsiService.RegisterSessionRequestBody();
            inValue.Body.playerName = playerName;
            return ((Client.PrsiService.WebServiceSoap)(this)).RegisterSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.PrsiService.JoinSessionResponse Client.PrsiService.WebServiceSoap.JoinSession(Client.PrsiService.JoinSessionRequest request) {
            return base.Channel.JoinSession(request);
        }
        
        public int JoinSession(string sessionName, string playerName) {
            Client.PrsiService.JoinSessionRequest inValue = new Client.PrsiService.JoinSessionRequest();
            inValue.Body = new Client.PrsiService.JoinSessionRequestBody();
            inValue.Body.sessionName = sessionName;
            inValue.Body.playerName = playerName;
            Client.PrsiService.JoinSessionResponse retVal = ((Client.PrsiService.WebServiceSoap)(this)).JoinSession(inValue);
            return retVal.Body.JoinSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.PrsiService.JoinSessionResponse> Client.PrsiService.WebServiceSoap.JoinSessionAsync(Client.PrsiService.JoinSessionRequest request) {
            return base.Channel.JoinSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.PrsiService.JoinSessionResponse> JoinSessionAsync(string sessionName, string playerName) {
            Client.PrsiService.JoinSessionRequest inValue = new Client.PrsiService.JoinSessionRequest();
            inValue.Body = new Client.PrsiService.JoinSessionRequestBody();
            inValue.Body.sessionName = sessionName;
            inValue.Body.playerName = playerName;
            return ((Client.PrsiService.WebServiceSoap)(this)).JoinSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.PrsiService.LeaveSessionResponse Client.PrsiService.WebServiceSoap.LeaveSession(Client.PrsiService.LeaveSessionRequest request) {
            return base.Channel.LeaveSession(request);
        }
        
        public void LeaveSession(string sessionName, int playerID) {
            Client.PrsiService.LeaveSessionRequest inValue = new Client.PrsiService.LeaveSessionRequest();
            inValue.Body = new Client.PrsiService.LeaveSessionRequestBody();
            inValue.Body.sessionName = sessionName;
            inValue.Body.playerID = playerID;
            Client.PrsiService.LeaveSessionResponse retVal = ((Client.PrsiService.WebServiceSoap)(this)).LeaveSession(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.PrsiService.LeaveSessionResponse> Client.PrsiService.WebServiceSoap.LeaveSessionAsync(Client.PrsiService.LeaveSessionRequest request) {
            return base.Channel.LeaveSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.PrsiService.LeaveSessionResponse> LeaveSessionAsync(string sessionName, int playerID) {
            Client.PrsiService.LeaveSessionRequest inValue = new Client.PrsiService.LeaveSessionRequest();
            inValue.Body = new Client.PrsiService.LeaveSessionRequestBody();
            inValue.Body.sessionName = sessionName;
            inValue.Body.playerID = playerID;
            return ((Client.PrsiService.WebServiceSoap)(this)).LeaveSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.PrsiService.StartGameResponse Client.PrsiService.WebServiceSoap.StartGame(Client.PrsiService.StartGameRequest request) {
            return base.Channel.StartGame(request);
        }
        
        public void StartGame(string sessionName, int playerID) {
            Client.PrsiService.StartGameRequest inValue = new Client.PrsiService.StartGameRequest();
            inValue.Body = new Client.PrsiService.StartGameRequestBody();
            inValue.Body.sessionName = sessionName;
            inValue.Body.playerID = playerID;
            Client.PrsiService.StartGameResponse retVal = ((Client.PrsiService.WebServiceSoap)(this)).StartGame(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.PrsiService.StartGameResponse> Client.PrsiService.WebServiceSoap.StartGameAsync(Client.PrsiService.StartGameRequest request) {
            return base.Channel.StartGameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.PrsiService.StartGameResponse> StartGameAsync(string sessionName, int playerID) {
            Client.PrsiService.StartGameRequest inValue = new Client.PrsiService.StartGameRequest();
            inValue.Body = new Client.PrsiService.StartGameRequestBody();
            inValue.Body.sessionName = sessionName;
            inValue.Body.playerID = playerID;
            return ((Client.PrsiService.WebServiceSoap)(this)).StartGameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.PrsiService.PlayCardResponse Client.PrsiService.WebServiceSoap.PlayCard(Client.PrsiService.PlayCardRequest request) {
            return base.Channel.PlayCard(request);
        }
        
        public void PlayCard(string sessionName, int playerID, Client.PrsiService.Card card) {
            Client.PrsiService.PlayCardRequest inValue = new Client.PrsiService.PlayCardRequest();
            inValue.Body = new Client.PrsiService.PlayCardRequestBody();
            inValue.Body.sessionName = sessionName;
            inValue.Body.playerID = playerID;
            inValue.Body.card = card;
            Client.PrsiService.PlayCardResponse retVal = ((Client.PrsiService.WebServiceSoap)(this)).PlayCard(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.PrsiService.PlayCardResponse> Client.PrsiService.WebServiceSoap.PlayCardAsync(Client.PrsiService.PlayCardRequest request) {
            return base.Channel.PlayCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.PrsiService.PlayCardResponse> PlayCardAsync(string sessionName, int playerID, Client.PrsiService.Card card) {
            Client.PrsiService.PlayCardRequest inValue = new Client.PrsiService.PlayCardRequest();
            inValue.Body = new Client.PrsiService.PlayCardRequestBody();
            inValue.Body.sessionName = sessionName;
            inValue.Body.playerID = playerID;
            inValue.Body.card = card;
            return ((Client.PrsiService.WebServiceSoap)(this)).PlayCardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.PrsiService.SkipTurnResponse Client.PrsiService.WebServiceSoap.SkipTurn(Client.PrsiService.SkipTurnRequest request) {
            return base.Channel.SkipTurn(request);
        }
        
        public void SkipTurn(string sessionName, int playerID) {
            Client.PrsiService.SkipTurnRequest inValue = new Client.PrsiService.SkipTurnRequest();
            inValue.Body = new Client.PrsiService.SkipTurnRequestBody();
            inValue.Body.sessionName = sessionName;
            inValue.Body.playerID = playerID;
            Client.PrsiService.SkipTurnResponse retVal = ((Client.PrsiService.WebServiceSoap)(this)).SkipTurn(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.PrsiService.SkipTurnResponse> Client.PrsiService.WebServiceSoap.SkipTurnAsync(Client.PrsiService.SkipTurnRequest request) {
            return base.Channel.SkipTurnAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.PrsiService.SkipTurnResponse> SkipTurnAsync(string sessionName, int playerID) {
            Client.PrsiService.SkipTurnRequest inValue = new Client.PrsiService.SkipTurnRequest();
            inValue.Body = new Client.PrsiService.SkipTurnRequestBody();
            inValue.Body.sessionName = sessionName;
            inValue.Body.playerID = playerID;
            return ((Client.PrsiService.WebServiceSoap)(this)).SkipTurnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.PrsiService.GetStateResponse Client.PrsiService.WebServiceSoap.GetState(Client.PrsiService.GetStateRequest request) {
            return base.Channel.GetState(request);
        }
        
        public Client.PrsiService.AppState GetState(string sessionName) {
            Client.PrsiService.GetStateRequest inValue = new Client.PrsiService.GetStateRequest();
            inValue.Body = new Client.PrsiService.GetStateRequestBody();
            inValue.Body.sessionName = sessionName;
            Client.PrsiService.GetStateResponse retVal = ((Client.PrsiService.WebServiceSoap)(this)).GetState(inValue);
            return retVal.Body.GetStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.PrsiService.GetStateResponse> Client.PrsiService.WebServiceSoap.GetStateAsync(Client.PrsiService.GetStateRequest request) {
            return base.Channel.GetStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.PrsiService.GetStateResponse> GetStateAsync(string sessionName) {
            Client.PrsiService.GetStateRequest inValue = new Client.PrsiService.GetStateRequest();
            inValue.Body = new Client.PrsiService.GetStateRequestBody();
            inValue.Body.sessionName = sessionName;
            return ((Client.PrsiService.WebServiceSoap)(this)).GetStateAsync(inValue);
        }
    }
}
