//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.PrsiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrsiService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name AddStringResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddString", ReplyAction="*")]
        Client.PrsiService.AddStringResponse AddString(Client.PrsiService.AddStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddString", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.PrsiService.AddStringResponse> AddStringAsync(Client.PrsiService.AddStringRequest request);
        
        // CODEGEN: Generating message contract since element name ReadStringResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadString", ReplyAction="*")]
        Client.PrsiService.ReadStringResponse ReadString(Client.PrsiService.ReadStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadString", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.PrsiService.ReadStringResponse> ReadStringAsync(Client.PrsiService.ReadStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddString", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.AddStringRequestBody Body;
        
        public AddStringRequest() {
        }
        
        public AddStringRequest(Client.PrsiService.AddStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddStringRequestBody {
        
        public AddStringRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.AddStringResponseBody Body;
        
        public AddStringResponse() {
        }
        
        public AddStringResponse(Client.PrsiService.AddStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddStringResult;
        
        public AddStringResponseBody() {
        }
        
        public AddStringResponseBody(string AddStringResult) {
            this.AddStringResult = AddStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadString", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.ReadStringRequestBody Body;
        
        public ReadStringRequest() {
        }
        
        public ReadStringRequest(Client.PrsiService.ReadStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReadStringRequestBody {
        
        public ReadStringRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.PrsiService.ReadStringResponseBody Body;
        
        public ReadStringResponse() {
        }
        
        public ReadStringResponse(Client.PrsiService.ReadStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReadStringResult;
        
        public ReadStringResponseBody() {
        }
        
        public ReadStringResponseBody(string ReadStringResult) {
            this.ReadStringResult = ReadStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Client.PrsiService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Client.PrsiService.WebServiceSoap>, Client.PrsiService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.PrsiService.AddStringResponse Client.PrsiService.WebServiceSoap.AddString(Client.PrsiService.AddStringRequest request) {
            return base.Channel.AddString(request);
        }
        
        public string AddString() {
            Client.PrsiService.AddStringRequest inValue = new Client.PrsiService.AddStringRequest();
            inValue.Body = new Client.PrsiService.AddStringRequestBody();
            Client.PrsiService.AddStringResponse retVal = ((Client.PrsiService.WebServiceSoap)(this)).AddString(inValue);
            return retVal.Body.AddStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.PrsiService.AddStringResponse> Client.PrsiService.WebServiceSoap.AddStringAsync(Client.PrsiService.AddStringRequest request) {
            return base.Channel.AddStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.PrsiService.AddStringResponse> AddStringAsync() {
            Client.PrsiService.AddStringRequest inValue = new Client.PrsiService.AddStringRequest();
            inValue.Body = new Client.PrsiService.AddStringRequestBody();
            return ((Client.PrsiService.WebServiceSoap)(this)).AddStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.PrsiService.ReadStringResponse Client.PrsiService.WebServiceSoap.ReadString(Client.PrsiService.ReadStringRequest request) {
            return base.Channel.ReadString(request);
        }
        
        public string ReadString() {
            Client.PrsiService.ReadStringRequest inValue = new Client.PrsiService.ReadStringRequest();
            inValue.Body = new Client.PrsiService.ReadStringRequestBody();
            Client.PrsiService.ReadStringResponse retVal = ((Client.PrsiService.WebServiceSoap)(this)).ReadString(inValue);
            return retVal.Body.ReadStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.PrsiService.ReadStringResponse> Client.PrsiService.WebServiceSoap.ReadStringAsync(Client.PrsiService.ReadStringRequest request) {
            return base.Channel.ReadStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.PrsiService.ReadStringResponse> ReadStringAsync() {
            Client.PrsiService.ReadStringRequest inValue = new Client.PrsiService.ReadStringRequest();
            inValue.Body = new Client.PrsiService.ReadStringRequestBody();
            return ((Client.PrsiService.WebServiceSoap)(this)).ReadStringAsync(inValue);
        }
    }
}
